baseURL = "https://www.tartandictionary.org/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "simpleness"
paginate = 20

title = "Tartan Dictionary"
enableInlineShortcodes = true
enableEmoji = true
googleAnalytics = ""

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2022"
  description = "A simple and concise hugo theme."
  disqus = ""

[params.valine]
  enable = false
  lang = 'en' 
  appId = ''
  appKey = ''
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  avatar = 'robohash'
  visitor = true
  serverURLS = 'https://abc123.api.lncldglobal.com'
  debug = false # display the visitor counts when using 'hugo server'

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
  [[menu.main]]
  name = "Families"
  url = "/families/"
  weight = 3
  [[menu.main]]
  name = "Patterns"
  url = "/patterns/"
  weight = 4
  [[menu.main]]
  name = "Tartans"
  url = "/tartans/"
  weight = 5
  [[menu.main]]
  name = "Variants"
  url = "/variants/"
  weight = 6
  [[menu.main]]
  name = "Stripes"
  url = "/stripes/"
  weight = 7
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 8

[social]
  github = "https://github.com/Drummonds"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"
tartan = "tartans"
stripe = "stripes"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    guessSyntax = true
    hl_Lines = ""
    # lineNoStart = 1
    # lineNos = true
    # lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4

    